alpha: 1.0
area_size: 3.0
batch_size: 256
beta: 10.0
buffer_size: 512
debug: false
deterministic: true
dyn_scale_path: Pretraining-ckpts/dynamics_norm_stats.npz
eval_epi: 5
eval_interval: 1
freeze_backbone: true
gamma: 0.0
gnn_layers: 1
history_len: 12
horizon: 6
inner_epoch: 8
labeling_horizon: 32
load_dir: null
load_step: null
log_dir: ./logs
loss_action_coef: 0.1
loss_dt_cbf_coef: 0.2
loss_dyn_coef: 0.0
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 3.0e-05
lr_cbf: 3.0e-05
lr_schedule: false
max_step: 256
n_env_test: 32
n_env_train: 16
n_obs: 6
n_rays: 32
n_sqp_iter: 25
name: cf_actor_head_only
num_agents: 1
pretrain_ckpt: Pretraining-ckpts/params_best_CF.pkl
relax_penalty: 1000.0
save_interval: 10
seed: 0
steps: 2000
alpha: 1.0
batch_size: 256
beta: 10.0
cbf_tgt_tau: 0.5
eps: 0.02
freeze_backbone: true
gamma: 0.0
gnn_layers: 1
horizon: 6
inner_epoch: 8
labeling_horizon: 32
loss_action_coef: 0.1
loss_dt_cbf_coef: 0.2
loss_dyn_coef: 0.0
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 3.0e-05
lr_cbf: 3.0e-05
max_grad_norm: 2.0
n_sqp_iter: 25
relax_penalty: 1000.0
seed: 0
sqp_horizon_len: 6
